pipeline {
    agent any
    tools { 
        M2 'Maven 3.9.2' 
        JDK 'jdk11' 
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2" = ${M2}"
                ''' 
            }
        }
    }
}
